spring.application.name=webliix

# Local DB--------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/webliix_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.flyway.baseline-on-migrate=true

# Server Port
server.port=8082

jwt.secret=webliix-super-secret-key-change-this-in-production-2026
jwt.expiration=604800000

# mail----------------------------------
spring.mail.host=smtp.zoho.in
spring.mail.port=587
spring.mail.username=contact@webliix.com
spring.mail.password=Y4AyXz1yuay1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# Storage configuration
storage.provider=local
storage.upload-dir=uploads

# Multipart File Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Cloudinary Configuration (External CDN & Media Storage)
cloudinary.url=${CLOUDINARY_URL:}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# MinIO configuration (optional)
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=webliix

# Redis configuration
spring.cache.type=redis
redis.host=localhost
redis.port=6379
redis.timeout=60000

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=Webliix
info.app.version=1.0.0
info.app.description=Webliix ERP CRM SaaS Platform