spring.application.name=webliix

# =========================================================
# SERVER
# =========================================================
server.port=${PORT:8082}

# =========================================================
# JPA
# =========================================================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =========================================================
# FLYWAY
# =========================================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false

# =========================================================
# FILE UPLOAD
# =========================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:20MB}

# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

management.info.env.enabled=false

info.app.name=Webliix
info.app.version=1.0.0
info.app.description=Webliix ERP CRM SaaS Platform