spring.application.name=webliix


# =========================================================
# SERVER
# =========================================================
server.port=${PORT:8082}

# =========================================================
# JWT
# =========================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:604800000}

# =========================================================
# MAIL
# =========================================================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# =========================================================
# FILE UPLOAD
# =========================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:100MB}

# =========================================================
# STORAGE
# =========================================================
storage.provider=${STORAGE_PROVIDER:local}
storage.upload-dir=${STORAGE_UPLOAD_DIR:uploads}

# =========================================================
# CLOUDINARY
# =========================================================
cloudinary.url=${CLOUDINARY_URL:}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# =========================================================
# REDIS
# =========================================================
spring.cache.type=${SPRING_CACHE_TYPE:redis}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:10s}
spring.data.redis.timeout=${REDIS_TIMEOUT:60s}

# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

management.info.env.enabled=true

info.app.name=Webliix
info.app.version=1.0.0
info.app.description=Webliix ERP CRM SaaS Platform