package com.webliix.automation.enums;

public enum TriggerType {
    LEAD_CREATED,
    LEAD_CONVERTED,
    PROJECT_CREATED,
    PROJECT_COMPLETED,
    QUOTATION_APPROVED,
    INVOICE_CREATED,
    INVOICE_PAID,
    PAYMENT_RECEIVED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    EMPLOYEE_CREATED,
    LEAVE_APPROVED,
    PAYROLL_GENERATED
}
