CREATE TABLE departments (
    id BIGSERIAL PRIMARY KEY,
    department_code VARCHAR(100) NOT NULL UNIQUE,
    department_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);